BEGIN;

CREATE TABLE IF NOT EXISTS "attendees" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  "member_id" BIGINT NOT NULL,
  "gathering_id" BIGINT NOT NULL,

  UNIQUE ("id")
);

ALTER TABLE
  "attendees"
ADD
  FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE CASCADE;

ALTER TABLE
  "attendees"
ADD
  FOREIGN KEY ("gathering_id") REFERENCES "gatherings" ("id") ON DELETE CASCADE;

COMMIT;