BEGIN;

CREATE TABLE IF NOT EXISTS "invitations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  "member_id" BIGINT NOT NULL,
  "gathering_id" BIGINT NOT NULL,
  "status" VARCHAR(20) NOT NULL,

  UNIQUE ("id")
);

-- index
CREATE INDEX "invitations_id_index" ON "invitations" ("id");

ALTER TABLE
  "invitations"
ADD
  FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE CASCADE;

ALTER TABLE
  "invitations"
ADD
  FOREIGN KEY ("gathering_id") REFERENCES "gatherings" ("id") ON DELETE CASCADE;

COMMIT;