// Code generated by MockGen. DO NOT EDIT.
// Source: gathering.go
//
// Generated by this command:
//
//	mockgen -source gathering.go -destination ../../mock/service/mock_gathering.go -package service
//
// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	domain "github.com/elangreza14/gathering/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockgatheringRepo is a mock of gatheringRepo interface.
type MockgatheringRepo struct {
	ctrl     *gomock.Controller
	recorder *MockgatheringRepoMockRecorder
}

// MockgatheringRepoMockRecorder is the mock recorder for MockgatheringRepo.
type MockgatheringRepoMockRecorder struct {
	mock *MockgatheringRepo
}

// NewMockgatheringRepo creates a new mock instance.
func NewMockgatheringRepo(ctrl *gomock.Controller) *MockgatheringRepo {
	mock := &MockgatheringRepo{ctrl: ctrl}
	mock.recorder = &MockgatheringRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgatheringRepo) EXPECT() *MockgatheringRepoMockRecorder {
	return m.recorder
}

// CreateAttendee mocks base method.
func (m *MockgatheringRepo) CreateAttendee(ctx context.Context, arg domain.Attendee) (*domain.Attendee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttendee", ctx, arg)
	ret0, _ := ret[0].(*domain.Attendee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttendee indicates an expected call of CreateAttendee.
func (mr *MockgatheringRepoMockRecorder) CreateAttendee(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttendee", reflect.TypeOf((*MockgatheringRepo)(nil).CreateAttendee), ctx, arg)
}

// CreateGathering mocks base method.
func (m *MockgatheringRepo) CreateGathering(ctx context.Context, arg domain.Gathering) (*domain.Gathering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGathering", ctx, arg)
	ret0, _ := ret[0].(*domain.Gathering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGathering indicates an expected call of CreateGathering.
func (mr *MockgatheringRepoMockRecorder) CreateGathering(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGathering", reflect.TypeOf((*MockgatheringRepo)(nil).CreateGathering), ctx, arg)
}

// CreateInvitations mocks base method.
func (m *MockgatheringRepo) CreateInvitations(ctx context.Context, gatheringID int64, status domain.InvitationStatus, memberID ...int64) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, gatheringID, status}
	for _, a := range memberID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInvitations", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvitations indicates an expected call of CreateInvitations.
func (mr *MockgatheringRepoMockRecorder) CreateInvitations(ctx, gatheringID, status any, memberID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, gatheringID, status}, memberID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitations", reflect.TypeOf((*MockgatheringRepo)(nil).CreateInvitations), varargs...)
}

// FindGatheringByID mocks base method.
func (m *MockgatheringRepo) FindGatheringByID(ctx context.Context, ID int64) (*domain.Gathering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGatheringByID", ctx, ID)
	ret0, _ := ret[0].(*domain.Gathering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindGatheringByID indicates an expected call of FindGatheringByID.
func (mr *MockgatheringRepoMockRecorder) FindGatheringByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGatheringByID", reflect.TypeOf((*MockgatheringRepo)(nil).FindGatheringByID), ctx, ID)
}

// FindInvitationByGatheringIDAndMemberID mocks base method.
func (m *MockgatheringRepo) FindInvitationByGatheringIDAndMemberID(ctx context.Context, gatheringID, memberID int64) (*domain.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInvitationByGatheringIDAndMemberID", ctx, gatheringID, memberID)
	ret0, _ := ret[0].(*domain.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInvitationByGatheringIDAndMemberID indicates an expected call of FindInvitationByGatheringIDAndMemberID.
func (mr *MockgatheringRepoMockRecorder) FindInvitationByGatheringIDAndMemberID(ctx, gatheringID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInvitationByGatheringIDAndMemberID", reflect.TypeOf((*MockgatheringRepo)(nil).FindInvitationByGatheringIDAndMemberID), ctx, gatheringID, memberID)
}

// FindMemberByID mocks base method.
func (m *MockgatheringRepo) FindMemberByID(ctx context.Context, ID int64) (*domain.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMemberByID", ctx, ID)
	ret0, _ := ret[0].(*domain.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMemberByID indicates an expected call of FindMemberByID.
func (mr *MockgatheringRepoMockRecorder) FindMemberByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMemberByID", reflect.TypeOf((*MockgatheringRepo)(nil).FindMemberByID), ctx, ID)
}
